import test from 'node:test';
import assert from 'node:assert/strict';
import {createPCMStore} from '../src/pcm-store.js';
const id='a'.repeat(24),month='2026-09';
function fixture(){
 const tables={publication:new Map([['current',{generation:'g1',chunks:['g1:0'],patient_count:1,billing_count:1}]]),sources:new Map([['g1:0',{generation:'g1',patients:[{id,patient:'Example, Morgan',current_candidate:true,collected:999999}],billing:[{id,month,billed:true,payment_received:true,collected:999999}]}]]),workflow:new Map(),members:new Map(),activities:new Map(),changes:new Map()};
 let mutex=Promise.resolve();
 const db={uid:()=> 'test-uid',timestamp:()=>new Date().toISOString(),get:async(b,id)=>tables[b].has(id)?{id,...structuredClone(tables[b].get(id))}:null,list:async(b,filter)=>[...tables[b]].map(([id,r])=>({id,...structuredClone(r)})).filter(r=>!filter||r[filter[0]]===filter[2]),transaction(fn){const task=mutex.then(async()=>{const writes=[];await fn({get:db.get,set:(b,id,d)=>writes.push([b,id,structuredClone(d)])});for(const [b,id,d] of writes)tables[b].set(id,d);});mutex=task.catch(()=>{});return task;}};
 return {tables,db,store:createPCMStore({db}),other:()=>createPCMStore({db})};
}
const save=(store,revision,values)=>store.api('/api/pcm/'+id+'/state',{method:'POST',body:JSON.stringify({revision,values,recorded_by:'forged'})});
test('shared staff view strips financial amounts',async()=>{const f=fixture();const r=await f.store.api('/api/pcm?month='+month);assert.equal(r.rows[0].payment_received,true);assert.ok(!JSON.stringify(r).includes('999999'));});
test('shared edits reject stale revisions and preserve an immutable change record',async()=>{const f=fixture();await save(f.store,0,{status:'enrolled'});const r=await f.other().api('/api/pcm/'+id+'?month='+month);assert.equal(r.state.status,'enrolled');assert.equal(r.state.recorded_by,'test-uid');assert.equal(f.tables.changes.size,1);assert.equal([...f.tables.changes.values()][0].previous.status,'candidate');await assert.rejects(save(f.other(),0,{status:'paused'}),/changed/);});
test('two simultaneous initial edits do not overwrite one another',async()=>{const f=fixture();const results=await Promise.allSettled([save(f.store,0,{status:'enrolled'}),save(f.other(),0,{status:'paused'})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.tables.changes.size,1);});
test('retrying an activity counts minutes once; a reused request with different contents fails',async()=>{const f=fixture();const body={month,actor:'Example staff',minutes:12,note:'Synthetic check',request_id:'12345678-1234-1234-1234-123456789012'};const call=b=>f.store.api('/api/pcm/'+id+'/activity',{method:'POST',body:JSON.stringify(b)});await Promise.all([call(body),call(body)]);assert.equal((await f.other().api('/api/pcm/'+id+'?month='+month)).logged_minutes,12);await assert.rejects(call({...body,minutes:13}),/changed/);});
test('incomplete publications are never presented',async()=>{const f=fixture();f.tables.sources.clear();await assert.rejects(f.store.api('/api/pcm'),/incomplete/);});
test('activity-only patients remain after leaving the candidate list',async()=>{const f=fixture();await f.store.api('/api/pcm/'+id+'/activity',{method:'POST',body:JSON.stringify({month,actor:'Example staff',minutes:5,note:'Synthetic',request_id:'12345678-1234-1234-1234-123456789012'})});f.tables.publication.get('current').patient_count=0;f.tables.sources.get('g1:0').patients=[];const r=await f.other().api('/api/pcm');assert.equal(r.rows[0].id,id);assert.equal(r.rows[0].current_candidate,false);});
