// Shared PCM worklist for the HRG console and the dedicated PCM workspace.
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = v => Math.round(v||0).toLocaleString('en-US');
const money = v => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0);
const dayLabel = d => d ? new Date(d.slice(0,10)+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}) : '—';
const monthLabel = m => new Date(m+'-01T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
const labels={candidate:'Candidate',review:'In review',outreach:'Outreach',enrolled:'Enrolled',paused:'Paused',declined:'Declined',not_started:'Not started',in_progress:'In progress',complete:'Work documented',ready_to_bill:'Ready for billing review',submitted:'Submitted'};
const badge = s => `<span class="badge ${esc(s)}">${esc(labels[s]||s)}</span>`;
function pagination(total,page,size){return `<div class="pagination"><small>${total?number(page*size+1)+'–'+number(Math.min((page+1)*size,total)):'0'} of ${number(total)} records</small><div><button id="prev-page" ${page===0?'disabled':''}>Previous</button><button id="next-page" ${(page+1)*size>=total?'disabled':''}>Next</button></div></div>`;}

export async function waitForRead(promise,timeoutMs=20000){
let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Loading took too long. Check your connection and try again.')),timeoutMs);})]);}finally{clearTimeout(timer);}
}

export function createPCM({api, openDialog, dialogVersion, toast, onSaved=async()=>{}, isActive=()=>true, showFinancials=true, loadTimeoutMs=20000}) {
let pcmRequest=0;
const state={pcmMonth:new Date().toLocaleDateString("en-CA",{timeZone:"America/Chicago"}).slice(0,7),pcmStatus:"all",pcmQuery:"",pcmPage:0};
function pcm(){return `<div id="pcm-summary" class="program-steps"><div class="pcm-load-status" role="status">Loading patients…</div></div><div class="card"><div class="card-head"><div><h2>The next action, for every patient</h2><p>Candidates require review. Enrollment is recorded explicitly and is never inferred from a claim.</p></div></div><div class="toolbar"><div class="search-field"><label for="pcm-search">Search patients, plans, conditions, or assignees</label><input id="pcm-search" type="search" placeholder="Find a patient or a group…" value="${esc(state.pcmQuery)}"></div><div><label for="pcm-month">Activity month</label><input id="pcm-month" type="month" value="${state.pcmMonth}"></div></div><div class="pill-tabs">${['all','candidate','review','outreach','enrolled','paused','declined'].map(s=>`<button data-pcm-status="${s}" aria-pressed="${state.pcmStatus===s}">${s==='all'?'Everyone':labels[s]}</button>`).join('')}</div><div id="pcm-table"></div></div><div class="notice">Prioritized by due follow-up, existing candidate tier, and recent clinic activity. Assign work to any team member; record the billing practitioner separately. Payment checkmarks reflect money received in NextGen.</div>`;}
function wire(){let timer;$('#pcm-search').oninput=e=>{state.pcmQuery=e.target.value;state.pcmPage=0;clearTimeout(timer);timer=setTimeout(loadPCM,200);};$('#pcm-month').onchange=e=>{if(e.target.value){state.pcmMonth=e.target.value;state.pcmPage=0;loadPCM();}};document.querySelectorAll('[data-pcm-status]').forEach(b=>b.onclick=()=>{state.pcmStatus=b.dataset.pcmStatus;state.pcmPage=0;document.querySelectorAll('[data-pcm-status]').forEach(el=>el.setAttribute('aria-pressed',el===b));loadPCM();});return loadPCM();}
async function loadPCM(){const serial=++pcmRequest;if(!isActive())return;$('#pcm-summary').setAttribute('aria-busy','true');$('#pcm-summary').innerHTML='<div class="pcm-load-status" role="status">Loading patients…</div>';$('#pcm-table').replaceChildren();try{const r=await waitForRead(api('/api/pcm?'+new URLSearchParams({month:state.pcmMonth,status:state.pcmStatus,q:state.pcmQuery,page:state.pcmPage})),loadTimeoutMs);if(serial!==pcmRequest||!isActive())return;$('#pcm-summary').innerHTML=[['Candidates',r.counts.candidate],['In review / outreach',r.counts.review+r.counts.outreach],['Enrolled',r.enrolled],['Billed this month',r.billed],['Payment received',r.payment_received],...(showFinancials ? [['Collections',money(r.collections)]] : [])].map(([l,v],i)=>`<div class="program-step ${i===2?'active':''}"><small>${l}</small><b>${typeof v==='number'?number(v):v}</b></div>`).join('');$('#pcm-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Patient / candidate evidence</th><th>Assigned to</th><th>Enrollment</th><th>Monthly work</th><th>Payment</th><th>Next action</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td><button class="text-button" data-patient="${x.id}">${esc(x.patient)}</button><small>${esc(x.cohorts)} · Last clinic ${dayLabel(x.last_visit)}</small></td><td>${esc(x.state.assigned_to||'Unassigned')}</td><td>${badge(x.state.status)}</td><td>${badge(x.monthly.status)}${x.billed?'<small>Claim recorded</small>':''}</td><td>${x.payment_received?'<span class="badge paid">✓ Received</span>':'<small>'+ (x.billed?'Awaiting payment':'No billed claim')+'</small>'}</td><td>${esc(x.state.next_action||'Review candidate')}<small>${x.state.follow_up?dayLabel(x.state.follow_up)+(x.follow_up_due?' · Due':''):''}</small></td></tr>`).join('')}</tbody></table></div>${!r.rows.length?'<div class="empty"><strong>No patients match this view.</strong>Change the status or search to see other patients.</div>':''}${pagination(r.total,r.page,25)}`;$('#prev-page').onclick=()=>{state.pcmPage--;loadPCM();};$('#next-page').onclick=()=>{state.pcmPage++;loadPCM();};document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>patientDetail(b.dataset.patient));}catch(e){if(serial!==pcmRequest||!isActive())return;const summary=$('#pcm-summary');if(summary){summary.innerHTML='<div class="pcm-load-status pcm-load-error" role="alert"><strong>Could not load the worklist.</strong><span>'+esc(e.message)+'</span><button id="pcm-retry">Retry loading</button></div>';$('#pcm-retry').onclick=loadPCM;}$('#pcm-table')?.replaceChildren();}finally{if(serial===pcmRequest&&isActive())$('#pcm-summary')?.setAttribute('aria-busy','false');}}
function field(label,name,value,type='text'){return `<div class="form-field"><label>${label}<input name="${name}" type="${type}" value="${esc(value||'')}"></label></div>`;}
function statusField(name,current,options){return `<div class="form-field"><label>Status<select name="${name}">${options.map(s=>`<option value="${s}" ${s===current?'selected':''}>${labels[s]}</option>`).join('')}</select></label></div>`;}
async function patientDetail(id){openDialog('Patient workflow','<div class="loading">Loading patient…</div>');const ticket=dialogVersion();try{const r=await waitForRead(api('/api/pcm/'+id+'?month='+state.pcmMonth),loadTimeoutMs);if(ticket!==dialogVersion()||!$('#detail').open)return;openDialog(r.patient,`<p class="card-subtitle">${esc(r.cohorts)} · ${esc(r.plan||'Plan not recorded')} · Last clinic ${dayLabel(r.last_visit)}</p>${r.current_candidate===false?'<div class="notice amber">Saved program member. This patient is absent from the latest source candidate list; prior evidence and your work are preserved below.</div>':''}<div class="notice">Candidate evidence: ${esc(r.dx_encounters||'—')} documented dates, ${dayLabel(r.first_dx)} – ${dayLabel(r.last_dx)}. ${r.previously_billed?'PCM was previously billed; enrollment still needs confirmation.':'No prior PCM claim in this dataset.'}</div><div class="dialog-grid">
 <section class="card"><div class="card-head"><h2>Enrollment & next action</h2></div><form id="patient-form"><div class="form-grid">${statusField('status',r.state.status,['candidate','review','outreach','enrolled','paused','declined'])}${field('Assigned to','assigned_to',r.state.assigned_to)}${field('Billing practitioner','billing_practitioner',r.state.billing_practitioner)}${field('Follow-up date','follow_up',r.state.follow_up,'date')}<div class="form-field full"><label>Next action<input name="next_action" value="${esc(r.state.next_action||'')}"></label></div><div class="form-field full"><label>Notes<textarea name="notes">${esc(r.state.notes||'')}</textarea></label></div></div><div class="form-footer"><button class="primary">Save enrollment</button><span class="form-error" role="alert"></span></div></form></section>
 <section class="card"><div class="card-head"><div><h2>${monthLabel(state.pcmMonth)}</h2><p>Monthly work & billing</p></div>${r.payment_received?'<span class="badge paid">✓ Payment received</span>':''}</div><form id="monthly-form"><div class="form-grid">${statusField('status',r.monthly.status,['not_started','in_progress','complete','ready_to_bill','submitted'])}${field('Assigned to','assigned_to',r.monthly.assigned_to)}<div class="form-field full"><label>Next action<input name="next_action" value="${esc(r.monthly.next_action||'')}"></label></div><div class="form-field full"><label>Monthly notes<textarea name="notes">${esc(r.monthly.notes||'')}</textarea></label></div></div><div class="form-footer"><button class="primary">Save monthly work</button><span class="form-error" role="alert"></span></div></form><div class="card-caption">${r.billed?'A PCM charge is recorded in NextGen.':'No PCM charge is recorded for this service month.'} ${r.payment_received?(showFinancials?'Payment received: '+money(r.collected)+'.':'Payment received.'):''}</div></section>
 <section class="card wide"><div class="card-head"><div><h2>Activity log</h2><p>Record who did the work. Logged time does not automatically mark a claim ready.</p></div><b>${number(r.logged_minutes)} min</b></div><form id="activity-form"><div class="form-grid">${field('Performed by','actor','')}${field('Minutes','minutes','', 'number')}<div class="form-field full"><label>Activity performed<textarea name="note" required></textarea></label></div></div><div class="form-footer"><button>Add activity</button><span class="form-error" role="alert"></span></div></form><div id="activities">${r.activities.map(a=>`<div class="activity-item"><b>${esc(a.actor)} · ${a.minutes} min</b><small>${esc(new Date(a.occurred).toLocaleString())}</small><p>${esc(a.note)}</p></div>`).join('')||'<div class="empty">No activity recorded for this month.</div>'}</div></section></div>`);
 const save=(form,action,revision)=>{const requestId=globalThis.crypto?.randomUUID?.() || '10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));$(form).onsubmit=async e=>{e.preventDefault();const el=e.currentTarget,values=Object.fromEntries(new FormData(el));const btn=el.querySelector('button');btn.disabled=true;try{const body=action==='activity'?{month:state.pcmMonth,request_id:requestId,...values,minutes:values.minutes===''?0:Number(values.minutes)}:{month:state.pcmMonth,revision,values};await api('/api/pcm/'+id+'/'+action,{method:'POST',body:JSON.stringify(body)});toast('Saved');await onSaved();if(isActive()){loadPCM();patientDetail(id);}}catch(error){el.querySelector('.form-error').textContent=error.message;btn.disabled=false;}};};save('#patient-form','state',r.state.revision);save('#monthly-form','monthly',r.monthly.revision);save('#activity-form','activity',0);
 }catch(e){if(ticket!==dialogVersion()||!$('#detail').open)return;openDialog('Patient workflow','<div class="notice error">'+esc(e.message)+'</div>');}}
return {render:pcm,wire,refresh:loadPCM,invalidate(){pcmRequest++;}};
}
